import sqlite3

class LFSSExceptionBase(Exception):...

class DatabaseLockedError(LFSSExceptionBase, sqlite3.DatabaseError):...

class PathNotFoundError(LFSSExceptionBase, FileNotFoundError):...

class PermissionDeniedError(LFSSExceptionBase, PermissionError):...

class InvalidPathError(LFSSExceptionBase, ValueError):...

class StorageExceededError(LFSSExceptionBase):...

class TooManyItemsError(LFSSExceptionBase):...