
class LFSSExceptionBase(Exception):...

class PermissionDeniedError(LFSSExceptionBase, PermissionError):...

class InvalidPathError(LFSSExceptionBase, ValueError):...

class StorageExceededError(LFSSExceptionBase):...