
class LFSSExceptionBase(Exception):...

class PathNotFoundError(LFSSExceptionBase, FileNotFoundError):...

class PermissionDeniedError(LFSSExceptionBase, PermissionError):...

class InvalidPathError(LFSSExceptionBase, ValueError):...

class StorageExceededError(LFSSExceptionBase):...

class TooManyItemsError(LFSSExceptionBase):...